import * as React from 'react';
import type { Metadata } from 'next';
import { ThemeProvider } from '@/app/contexts/theme-context';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="font-sans antialiased min-h-screen relative overflow-x-hidden">
                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
